### ISSUE TITLE
Why do I get the following error when I run this script in Python?

### ISSUE THREAD

**Issue by jianfeidexiaotaiyang** [eason1021/Martensite-Variants-Identification-Method#1]
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Traceback (most recent call last):
  File "E:/NiTi/mashitibianti/1/Martensite-Variants-Identification-Method-master/MVIM.py", line 763, in <module>
    mvim_2 = mvim(frame_index, data_2, ref_list_type2, rotation_angle, rotation_axis, pbc_setting, switch)
  File "E:/NiTi/mashitibianti/1/Martensite-Variants-Identification-Method-master/MVIM.py", line 308, in mvim
    m_o_f_x = np.dot(phase_vector_x,ref[transform_matrix][0])
IndexError: list index out of range

Process finished with exit code 1

**Comment by eason1021** [comment]
Hi, this is my first time to see this error, and I can ensure what factors caused it.

However, as the message displayed, it happened on line 308 when processing the type 2 atom.
I think you can check your length of transformation matrix or particle number at first.
Maybe the number of atoms has changed during your simulation process.

**Comment by jianfeidexiaotaiyang** [comment]
> Hi, this is my first time to see this error, and I can ensure what factors caused it.
> 
> However, as the message displayed, it happened on line 308 when processing the type 2 atom.
> I think you can check your length of transformation matrix or particle number at first.
> Maybe the number of atoms has changed during your simulation process.




In fact, I ran the 'example-data' you gave on this website and the error occurred.
![image](https://user-images.githubusercontent.com/83405976/128599473-b57150c4-ccee-4d6d-ab07-d2b741eae610.png)
But I don't know why.
Thanks and looking forward to your reply!

**Comment by eason1021** [comment]
Hello, thanks for your kind feedback, and I feel so sorry that I made such a mistake.

I find that the initial reference file has some problem, and I have fixed it to the correct one. Now, you can re-pull the repo and use the new reference file. Everything will be OK.

Thank you again for your correction, and I'm sorry for delaying your time.

Best regards,
Eason

**Comment by smith-shine** [comment]
Hello, Professor Eason, I ran the 'example-data' you gave on this website and the following error occurred:
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.
Failed to find a square root.

Is such an error normal? Thanks and looking forward to your reply!

**Comment by eason1021** [comment]
Dear Smith,

Hi, I am YiMing.
This warning results from the code could not calculate  the square root
from the given matrix and it would find out the approximate number
automatically. Hence, you could ignore this warning message, it is normal.

Best regards,
YiMing

smith-shine ***@***.***>於 2022年4月18日 週一，16:13寫道：

**Comment by smith-shine** [comment]
Dear YiMing,
  Thank you for your reply and selfless sharing. 

Best wishes!
Smith

**Comment by maylight1** [comment]
Hello, Professor Eason, I ran the 'example-data' you gave on this website and the following error occurred:

D:\program\python\python.exe D:/MVIM/MVIM.py
Traceback (most recent call last):
  File "D:\MVIM\MVIM.py", line 34, in <module>
    node_1.modifiers.append(SelectParticleTypeModifier(property='Particle Type', types={2}))
NameError: name 'SelectParticleTypeModifier' is not defined

Process finished with exit code 1


Thanks and looking forward to your reply!

**Comment by maylight1** [comment]
I've already solved the problem. The reason for this problem is that the version of Ovito I use is different from yours.Thank you for your selfless sharing.
